// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6j-iJwEauHhmX7_A3SSWYTqG6wOdlbPg',
    appId: '1:260144730620:web:9a2a08e98d9d97c1752279',
    messagingSenderId: '260144730620',
    projectId: 'movies-app-59407',
    authDomain: 'movies-app-59407.firebaseapp.com',
    storageBucket: 'movies-app-59407.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc-R4e-gFVMyh4fe6wyigugtuwqkIpW3Y',
    appId: '1:260144730620:android:c2463916059bd21b752279',
    messagingSenderId: '260144730620',
    projectId: 'movies-app-59407',
    storageBucket: 'movies-app-59407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGUyYKJ5Ni8DdXeMIYMOHO4UiTve20aq8',
    appId: '1:260144730620:ios:48d9fdc80f90859e752279',
    messagingSenderId: '260144730620',
    projectId: 'movies-app-59407',
    storageBucket: 'movies-app-59407.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGUyYKJ5Ni8DdXeMIYMOHO4UiTve20aq8',
    appId: '1:260144730620:ios:48d9fdc80f90859e752279',
    messagingSenderId: '260144730620',
    projectId: 'movies-app-59407',
    storageBucket: 'movies-app-59407.firebasestorage.app',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6j-iJwEauHhmX7_A3SSWYTqG6wOdlbPg',
    appId: '1:260144730620:web:4cd9ac0955e56c42752279',
    messagingSenderId: '260144730620',
    projectId: 'movies-app-59407',
    authDomain: 'movies-app-59407.firebaseapp.com',
    storageBucket: 'movies-app-59407.firebasestorage.app',
  );
}
