import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'screens/movies_list_screen.dart';
import 'firebase_options.dart'; // Generated by flutterfire CLI

void main() async {
  WidgetsFlutterBinding.ensureInitialized(); // required for async main
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Movies App',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MoviesListScreen(currentUserId: "testUserId"),
    );
  }
}
